version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: foodify-postgres
    ports:
      - 6500:5432
    volumes:
      - postgresDB:/data/postgres
    env_file:
      - ./.env

  redis:
    image: redis:alpine
    container_name: foodify-redis
    ports:
      - 6379:6379
    volumes:
      - redisDB:/data

volumes:
  postgresDB:
  redisDB:
